#!/bin/sh
set xe

echo 'Installing dependecies for either redhat based distros or debian based'

which apt-get

if [ $? != 0 ]; then
  echo 'apt not found checking yum'

  which yum
  if [ $? != 0 ]; then
    echo 'yum not found...is this Darwin?'
    
    if [ $(uname) == 'Darwin' ]; then
      echo 'Yep its Darwin...making sure xcode is installed via xcode-select --install'
      xcode-select --install
      echo 'This will fail if already install that is ok!'
    else
      echo 'Unsupport OS....bailing!'
      exit 1
    fi
  else
    sudo yum install gcc gcc-c++ make flex bison gperf ruby freetype-devel fontconfig-devel libicu-devel sqlite-devel libpng-devel libjpeg-devel
  fi
else
  sudo add-apt-repository multiverse
  sudo apt-get update
  sudo apt-get -y install build-essential g++ flex bison gperf ruby perl libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev libjpeg-dev libx11-dev libxext-dev ttf-mscorefonts-installer python2 python2-as-python
fi

echo 'Making sure we are on 2.1.1-multi git branck of bgrahamclickup/phantomjs branch'

git rev-parse --abbrev-ref HEAD | grep '2.1.1-multi' &> /dev/null
if [ $? != 0 ]; then
  echo 'Not on right branch!!!'
  exit 1
fi

echo 'Initing submodules'

git submodule init
git submodule update

echo 'patching qt'

rm ./src/qt/qtwebkit/Source/JavaScriptCore/API/JSStringRef.h
cp ./patched/JSStringRef.h ./src/qt/qtwebkit/Source/JavaScriptCore/API/

rm ./src/qt/qtwebkit/Source/WebCore/dom/Document.cpp
cp ./patched/Document.cpp ./src/qt/qtwebkit/Source/WebCore/dom/

rm ./src/qt/qtwebkit/Source/WebCore/platform/graphics/SegmentedFontData.cpp
cp ./patched/SegmentedFontData.cpp ./src/qt/qtwebkit/Source/WebCore/platform/graphics/

rm ./src/qt/qtwebkit/Source/JavaScriptCore/API/JSStringRef.cpp
cp ./patched/JSStringRef.cpp ./src/qt/qtwebkit/Source/JavaScriptCore/API/

rm ./src/qt/qtwebkit/Source/JavaScriptCore/runtime/DateConversion.cpp
cp ./patched/DateConversion.cpp ./src/qt/qtwebkit/Source/JavaScriptCore/runtime/

rm ./src/qt/qtwebkit/Source/WebKit2/Shared/API/c/WKString.cpp
cp ./patched/WKString.cpp ./src/qt/qtwebkit/Source/WebKit2/Shared/API/c/

rm ./src/qt/qtwebkit/Source/WTF/wtf/TypeTraits.h
cp ./patched/TypeTraits.h ./src/qt/qtwebkit/Source/WTF/wtf/

echo 'Building OpenSSL'
cd ./openssl-1.0.2u
./makeall
cd ..

echo 'Building Phaontomjs'
./build.py
