#!/bin/sh

echo 'Building, testing, and local-installing openssl'

echo 'Configuring openssl'
./config --prefix=$PWD/sslinstall --openssldir=$PWD/sslinstall

echo 'Building openssl'
make

echo 'Testing openssl'
make test

echo 'Local installing openssl'
make install
