#!/bin/sh

echo 'Building, testing, and local-installing openssl'

if [ $(uname) == 'Darwin' ]; then
  echo 'Darwin detected, do you want to build intel64 or arm64 (i or a): \c'

  read type

  if [ $type == 'i' ]; then
    echo 'Configuring for Darwin Intel'
    ./Configure darwin64-x86_64-cc --prefix=$PWD/sslinstall --openssldir=$PWD/sslinstall
  elif [ $type == 'a' ]; then
    echo 'Configuring for Darwin Arm'
     ./Configure enable-rc5 zlib no-asm darwin64-arm64-cc --prefix=$PWD/sslinstall --openssldir=$PWD/sslinstall
  else
    echo 'Bad input...bailing'
    exit 1
  fi
else 
  echo 'Configuring openssl for Linux'
  ./config --prefix=$PWD/sslinstall --openssldir=$PWD/sslinstall
fi

exit
echo 'Building openssl'
make

echo 'Testing openssl'
make test

echo 'Local installing openssl'
make install
